# Generated by Django 4.2.1 on 2023-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_alter_car_produced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description_en',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_ru',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_uz',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_en',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_ru',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_uz',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
