# Generated by Django 4.2.1 on 2023-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_alter_image_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=2000)),
                ('name_en', models.CharField(max_length=2000)),
                ('name_ru', models.CharField(max_length=2000)),
                ('description_uz', models.CharField(blank=True, max_length=50000, null=True)),
                ('description_en', models.CharField(blank=True, max_length=50000, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=50000, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=2000)),
                ('name_en', models.CharField(max_length=2000)),
                ('name_ru', models.CharField(max_length=2000)),
                ('description_uz', models.CharField(blank=True, max_length=50000, null=True)),
                ('description_en', models.CharField(blank=True, max_length=50000, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=50000, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
