# Generated by Django 4.2.1 on 2023-10-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=2000)),
                ('name_en', models.CharField(max_length=2000)),
                ('name_ru', models.CharField(max_length=2000)),
                ('description_uz', models.TextField(max_length=5000)),
                ('description_en', models.TextField(max_length=5000)),
                ('description_ru', models.TextField(max_length=5000)),
                ('image', models.FileField(null=True, upload_to='')),
                ('link', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
