# Generated by Django 4.2.1 on 2023-10-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0007_cardetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='cardetail',
            name='description_uz',
        ),
    ]
