# Generated by Django 4.2.1 on 2023-10-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0008_remove_cardetail_description_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDetail',
            new_name='Slider',
        ),
    ]
